export const CONTEXT = '/api/admin'

// 七牛域名，结尾带斜杠
export const QiniuDomain = 'http://rnwwnc95c.hn-bkt.clouddn.com/'
export const ShenFenZhengPrefix = 'demo/'

export const LOGIN = CONTEXT + '/auth/login'
export const LOGIN_USER = CONTEXT + '/login/user'
export const LOGOUT = CONTEXT + '/auth/logout'
export const UP_TOKEN = CONTEXT + '/index/uptoken'
export const GOODS = CONTEXT + '/goods'
export const SPECIFICATION = CONTEXT + '/specification'
export const CATEGORY = CONTEXT + '/category'
export const BRAND = CONTEXT + '/brand'
export const CUSTOMER = CONTEXT + '/user'
export const INVOICE = CONTEXT + '/invoice'
export const ADDRESS = CONTEXT + '/address'
export const REGION = CONTEXT + '/region'
export const ORDER = CONTEXT + '/order'
export const COURIER = CONTEXT + '/shipper'
export const COUPON = CONTEXT + '/coupon'
export const TOPIC = CONTEXT + '/topic'
export const ADVERTISEMENT = CONTEXT + '/advertisement'
export const EMPLOYEE = CONTEXT + '/admin'
